# Generated by Django 3.1.7 on 2021-06-18 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPageSectionsOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayedCategories', models.ManyToManyField(blank=True, related_name='categoryDCBPSO', to='videoBlogApp.categoryOptions')),
                ('displayedSubCategories', models.ManyToManyField(blank=True, related_name='subCategoryDCBPSO', to='videoBlogApp.subCategoryOptions')),
            ],
            options={
                'verbose_name_plural': 'Do Not Touch This Model-1',
            },
        ),
    ]
