# Generated by Django 3.1.7 on 2021-06-18 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoBlogApp', '0002_blogpagesectionsordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpagesectionsordering',
            name='lastUpdateBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorDCBPSO', to=settings.AUTH_USER_MODEL),
        ),
    ]
