# Generated by Django 3.1.7 on 2021-06-22 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoBlogApp', '0004_auto_20210619_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingdata',
            name='lastUpdateBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastUpdateByMD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketingdata',
            name='latestByDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
