# Generated by Django 3.1.7 on 2021-06-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0005_auto_20210622_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingdata',
            name='hitCountPopular',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
