# Generated by Django 3.1.7 on 2021-06-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0008_auto_20210622_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingdata',
            name='latestByDate',
            field=models.TextField(),
        ),
    ]
