# Generated by Django 3.1.7 on 2021-06-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0009_auto_20210622_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingdata',
            name='latestByDate',
            field=models.PositiveIntegerField(),
        ),
    ]
