# Generated by Django 3.1.7 on 2021-06-23 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0010_auto_20210622_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideos',
            name='releasedDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
