# Generated by Django 3.1.7 on 2021-06-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0011_blogvideos_releaseddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideos',
            name='metaDescriptionVideo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogvideos',
            name='metaKeywordsVideo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blogvideos',
            name='metaTitleVideo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='blogvideos',
            name='tagsVideo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
