# Generated by Django 3.1.7 on 2021-06-25 07:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0013_auto_20210624_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogVideoDetailedDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitleVideo', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaDescriptionVideo', models.TextField(blank=True, null=True)),
                ('metaKeywordsVideo', models.TextField(blank=True, null=True)),
                ('tagsVideo', models.CharField(blank=True, max_length=1000, null=True)),
                ('featuredImage', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('blogProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogProfileNameBVDDM', to='videoBlogApp.blogvideos')),
            ],
            options={
                'verbose_name_plural': 'Blog Video Detailed DM',
            },
        ),
        migrations.CreateModel(
            name='blogVideoListingDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitleVideo', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaDescriptionVideo', models.TextField(blank=True, null=True)),
                ('metaKeywordsVideo', models.TextField(blank=True, null=True)),
                ('tagsVideo', models.CharField(blank=True, max_length=1000, null=True)),
                ('featuredImage', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('blogProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='blogProfileNameBVLDM', to='videoBlogApp.blogvideos')),
            ],
            options={
                'verbose_name_plural': 'Blog Video Listing DM',
            },
        ),
        migrations.DeleteModel(
            name='blogVideoDM',
        ),
    ]
