# Generated by Django 3.1.7 on 2021-06-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0014_auto_20210625_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogvideolistingdm',
            name='blogProfileName',
        ),
    ]
