# Generated by Django 3.1.7 on 2021-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0021_fundingdetailsvisibility'),
        ('videoBlogApp', '0017_marketingdata_maxlimitforexplore'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideos',
            name='relatedResearchReports',
            field=models.ManyToManyField(blank=True, related_name='relatedResearchReportsBV', to='stockApp.stockBasicDetail'),
        ),
    ]
