# Generated by Django 3.1.7 on 2021-07-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0018_blogvideos_relatedresearchreports'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideos',
            name='excerptContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
