# Generated by Django 3.1.7 on 2022-02-26 19:00

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('videoBlogApp', '0019_blogvideos_excerptcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogvideolistingdm',
            name='tagsVideo',
        ),
        migrations.AddField(
            model_name='blogvideolistingdm',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
