# Generated by Django 3.1.7 on 2022-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0020_auto_20220227_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideos',
            name='showinpitch',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
