# Generated by Django 3.1.7 on 2022-09-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoBlogApp', '0021_blogvideos_showinpitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideos',
            name='showinhead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
