# Generated by Django 3.1.7 on 2022-01-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productPagesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlyfundingappfeature',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundraisingjourney',
            name='excerptContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingappfeature',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='growthfundraisingjourney',
            name='excerptContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingappfeature',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seedfundraisingjourney',
            name='excerptContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
