# Generated by Django 3.1.7 on 2022-01-23 11:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productPagesApp', '0002_auto_20220119_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='earlyfundingpackages',
            old_name='amount',
            new_name='equityResearchReportAmount',
        ),
        migrations.RenameField(
            model_name='earlyfundingpackages',
            old_name='image',
            new_name='equityResearchReportImage',
        ),
        migrations.RenameField(
            model_name='earlyfundingpackages',
            old_name='image_alt_tag',
            new_name='equityResearchReportImage_alt_tag',
        ),
        migrations.RenameField(
            model_name='growthfundingpackages',
            old_name='amount',
            new_name='equityResearchReportAmount',
        ),
        migrations.RenameField(
            model_name='growthfundingpackages',
            old_name='image',
            new_name='equityResearchReportImage',
        ),
        migrations.RenameField(
            model_name='growthfundingpackages',
            old_name='image_alt_tag',
            new_name='equityResearchReportImage_alt_tag',
        ),
        migrations.RenameField(
            model_name='seedfundingpackages',
            old_name='amount',
            new_name='equityResearchReportAmount',
        ),
        migrations.RenameField(
            model_name='seedfundingpackages',
            old_name='image',
            new_name='equityResearchReportImage',
        ),
        migrations.RenameField(
            model_name='seedfundingpackages',
            old_name='image_alt_tag',
            new_name='equityResearchReportImage_alt_tag',
        ),
        migrations.RemoveField(
            model_name='earlyfundingpackages',
            name='button_ActionUrl',
        ),
        migrations.RemoveField(
            model_name='earlyfundingpackages',
            name='details',
        ),
        migrations.RemoveField(
            model_name='earlyfundingpackages',
            name='packagesType',
        ),
        migrations.RemoveField(
            model_name='growthfundingpackages',
            name='button_1_ActionUrl',
        ),
        migrations.RemoveField(
            model_name='growthfundingpackages',
            name='details',
        ),
        migrations.RemoveField(
            model_name='growthfundingpackages',
            name='packagesType',
        ),
        migrations.RemoveField(
            model_name='seedfundingpackages',
            name='button_ActionUrl',
        ),
        migrations.RemoveField(
            model_name='seedfundingpackages',
            name='details',
        ),
        migrations.RemoveField(
            model_name='seedfundingpackages',
            name='packagesType',
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='equityResearchReportTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='equityRestructuringAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='equityRestructuringImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='equityRestructuringImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='equityRestructuringTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='investmentDeckAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='investmentDeckImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='investmentDeckImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='investmentDeckTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='pitchDeckAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='pitchDeckImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='pitchDeckImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='pitchDeckTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='projectionsAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='projectionsImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='projectionsImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='projectionsTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='valuationReportAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='valuationReportImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='valuationReportImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='earlyfundingpackages',
            name='valuationReportTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='equityResearchReportTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='equityRestructuringAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='equityRestructuringImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='equityRestructuringImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='equityRestructuringTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='investmentDeckAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='investmentDeckImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='investmentDeckImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='investmentDeckTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='pitchDeckAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='pitchDeckImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='pitchDeckImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='pitchDeckTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='projectionsAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='projectionsImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='projectionsImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='projectionsTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='valuationReportAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='valuationReportImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='valuationReportImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingpackages',
            name='valuationReportTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='equityResearchReportTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='equityRestructuringAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='equityRestructuringImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='equityRestructuringImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='equityRestructuringTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='investmentDeckAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='investmentDeckImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='investmentDeckImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='investmentDeckTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='pitchDeckAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='pitchDeckImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='pitchDeckImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='pitchDeckTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='projectionsAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='projectionsImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='projectionsImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='projectionsTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='valuationReportAmount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='valuationReportImage',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='valuationReportImage_alt_tag',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingpackages',
            name='valuationReportTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sellesopappfeatures',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sellesopjourney',
            name='excerptContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earlyfundingfaqs',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='earlyfundingpackages',
            name='duration',
            field=models.CharField(choices=[('one_off', 'One Off'), ('premium', 'Premium')], default='one_off', max_length=10),
        ),
        migrations.AlterField(
            model_name='growthfundingfaqs',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='growthfundingpackages',
            name='duration',
            field=models.CharField(choices=[('one_off', 'One Off'), ('premium', 'Premium')], default='one_off', max_length=10),
        ),
        migrations.AlterField(
            model_name='seedfundingpackages',
            name='duration',
            field=models.CharField(choices=[('one_off', 'One Off'), ('premium', 'Premium')], default='one_off', max_length=10),
        ),
        migrations.AlterField(
            model_name='sellesopfaqs',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sellyourstartupfaqs',
            name='answers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
