# Generated by Django 3.1.7 on 2022-01-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productPagesApp', '0003_auto_20220123_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellesopaboutus',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sellesopfinewordsaboutus',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
