# Generated by Django 3.1.7 on 2022-02-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productPagesApp', '0004_auto_20220129_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sellesopfinewordsaboutus',
            name='image',
        ),
        migrations.RemoveField(
            model_name='sellesopfinewordsaboutus',
            name='image_alt_tag',
        ),
        migrations.AddField(
            model_name='sellesopfinewordsaboutus',
            name='upload_Gif',
            field=models.FileField(blank=True, null=True, upload_to='videos/gif'),
        ),
    ]
