# Generated by Django 3.1.7 on 2022-03-27 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productPagesApp', '0005_auto_20220203_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedfundingpackages',
            name='equityRestructuringAmount',
        ),
        migrations.RemoveField(
            model_name='seedfundingpackages',
            name='projectionsAmount',
        ),
    ]
