# Generated by Django 3.1.7 on 2022-04-10 17:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0047_auto_20220410_2246'),
        ('employeeApp', '0030_auto_20220410_2246'),
        ('productPagesApp', '0006_auto_20220327_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='privateBoutiqueCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('category', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stockApp.categoryoptions')),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Categories',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueContactDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaTags', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaFeaturedImage', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('metaKeywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Contact DM',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('mobile', models.BigIntegerField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.city')),
                ('countryCode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.country')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employeeApp.state')),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Contact Us Form',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueContactUsBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerImage', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('bannerImage_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Contact Us Banner',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueContactUsKnowMore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excerptContent', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Contact Us Know More',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueContactUsKnowMoreFAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Contact Us Know More FAQs',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueInvestingProcessCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('imageOnHover', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('cardContent', models.TextField(blank=True, null=True)),
                ('image_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('imageOnHover_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Investing Process Cards',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueInvestingProcessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('image_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Investing Process Image',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueRunningCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardImage', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('cardImage_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Running Cards',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueSellingProcessCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('imageOnHover', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('cardContent', models.TextField(blank=True, null=True)),
                ('image_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('imageOnHover_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Selling Process Cards',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueSellingProcessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('image_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Selling Process Image',
            },
        ),
        migrations.CreateModel(
            name='privateBoutiqueWhyToInvestCards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('image_alt_tag', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Private Boutique Why To Invest Cards',
            },
        ),
        migrations.DeleteModel(
            name='privateBoutiqueInvestingProcess',
        ),
        migrations.DeleteModel(
            name='privateBoutiquePrivateShares',
        ),
        migrations.DeleteModel(
            name='privateBoutiqueSellingProcess',
        ),
        migrations.DeleteModel(
            name='privateBoutiqueWhyToInvest',
        ),
        migrations.AlterModelOptions(
            name='privateboutiquefaqinvestment',
            options={'verbose_name_plural': 'Private Boutique FAQs Investment'},
        ),
        migrations.AlterModelOptions(
            name='privateboutiquefaqtaximplications',
            options={'verbose_name_plural': 'Private Boutique FAQs Tax Implications'},
        ),
        migrations.RemoveField(
            model_name='privateboutiquebanner',
            name='sectionImage',
        ),
        migrations.RemoveField(
            model_name='privateboutiquebanner',
            name='sectionImage_alt_tag',
        ),
        migrations.RemoveField(
            model_name='privateboutiquesuccessstories',
            name='author',
        ),
        migrations.RemoveField(
            model_name='privateboutiquesuccessstories',
            name='successStoriesImage',
        ),
        migrations.RemoveField(
            model_name='privateboutiquesuccessstories',
            name='successStoriesImage_alt_tag',
        ),
        migrations.AddField(
            model_name='privateboutiquebanner',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privateboutiquebanner',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='privateboutiquesuccessstories',
            name='investmentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='privateboutiquesuccessstories',
            name='ipoBandPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='privateboutiquesuccessstories',
            name='listingPrice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='privateboutiquesuccessstories',
            name='presentPrice',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='This will be visible only if we are not able to fetch Price from Screener or Planify Marketplace', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='privateboutiquesuccessstories',
            name='stockLogo',
            field=models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AddField(
            model_name='privateboutiquesuccessstories',
            name='stockLogo_alt_tag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privateboutiquesuccessstories',
            name='stockName',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockNamePBSS', to='stockApp.stockbasicdetail'),
        ),
        migrations.AlterField(
            model_name='privateboutiquefaqinvestment',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privateboutiquefaqtaximplications',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='privateboutiquesuccessstories',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
