# Generated by Django 3.1.7 on 2022-04-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productPagesApp', '0007_auto_20220410_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='earlyfundingcontactusknowmore',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='growthfundingcontactusknowmore',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='privateboutiquecontactusknowmore',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='seedfundingcontactusknowmore',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sellesopcontactusknowmore',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sellyourstartupcontactusknowmore',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
