# Generated by Django 3.1.7 on 2021-07-23 23:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogHomeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='homeBlogDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitleListing', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaDescriptionListing', models.TextField(blank=True, null=True)),
                ('metaKeywordsListing', models.TextField(blank=True, null=True)),
                ('tagsListing', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaFeaturedImage', models.ImageField(blank=True, null=True, upload_to='media/images/featured')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Blog Home DM Information',
            },
        ),
    ]
