# Generated by Django 3.1.7 on 2022-04-10 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name_plural': 'Users Profile Roles',
            },
        ),
        migrations.CreateModel(
            name='userRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_ownerUR', to=settings.AUTH_USER_MODEL)),
                ('profile_roles', models.ManyToManyField(to='authApp.roles')),
            ],
            options={
                'verbose_name_plural': 'Users and Their Profiles',
            },
        ),
    ]
