# Generated by Django 3.1.7 on 2022-04-23 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userroles',
            options={'verbose_name_plural': 'Users, Username and Profiles Roles'},
        ),
        migrations.AddField(
            model_name='userroles',
            name='profile_username',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='referred_by_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='userroles',
            name='referred_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
