# Generated by Django 3.1.7 on 2022-05-14 18:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0002_auto_20220423_2124'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginBannerObjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOne', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentOne', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleOneImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleOneImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('titleTwo', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentTwo', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleTwoImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleTwoImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('titleThree', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentThree', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleThreeImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleThreeImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('titleFour', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentFour', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleFourImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleFourImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('bannerImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('bannerImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('videoID', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('relatedTo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='loginBannerOb', to='authApp.roles')),
            ],
            options={
                'verbose_name_plural': 'login banner objects',
            },
        ),
    ]
