# Generated by Django 3.1.7 on 2022-08-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_loginbannerobjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginbannerobjects',
            name='contentFive',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='contentSix',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='titleFive',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='titleFiveImg',
            field=models.ImageField(blank=True, null=True, upload_to='login/images'),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='titleFiveImg_AltTag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='titleSix',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='titleSixImg',
            field=models.ImageField(blank=True, null=True, upload_to='login/images'),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='titleSixImg_AltTag',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='videoContent',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='loginbannerobjects',
            name='videoTitle',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
