# Generated by Django 3.1.7 on 2022-09-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_auto_20220820_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('body', models.TextField()),
                ('title', models.TextField()),
                ('template_type', models.CharField(max_length=100)),
                ('template_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('platform', models.CharField(default='NA', max_length=10)),
                ('token', models.TextField()),
                ('device_id', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserLogoutHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('platform', models.CharField(default='NA', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField()),
            ],
        ),
    ]
