# Generated by Django 3.1.7 on 2021-06-17 18:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='employeeAccountType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Employee Company Details',
            },
        ),
        migrations.CreateModel(
            name='employeeDepartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Employee Department Details',
            },
        ),
        migrations.CreateModel(
            name='employeeGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Employee Grade Details',
            },
        ),
        migrations.CreateModel(
            name='employeeRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Employee Role Details',
            },
        ),
        migrations.CreateModel(
            name='employeeTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Employee Type Details',
            },
        ),
        migrations.CreateModel(
            name='uploadDocuments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePhoto', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('aadharCard', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('panCard', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('cancelCheque', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('degree', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('assetDocument', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('experienceLetter', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('recommendationLetter', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorEUD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Upload Documents Details',
            },
        ),
        migrations.CreateModel(
            name='employeePersonalDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=1000)),
                ('lastName', models.CharField(blank=True, max_length=1000, null=True)),
                ('personalEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('mobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('alternateMobileNumber', models.BigIntegerField(blank=True, null=True)),
                ('aadharNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('panNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('maritalStatus', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Seperated', 'Seperated'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=50, null=True)),
                ('educationDetails', models.CharField(blank=True, max_length=1000, null=True)),
                ('highestQualification', models.CharField(blank=True, choices=[('Graduate', 'Graduate'), ('PostGraduate', 'PostGraduate'), ('UnderGraduate', 'Graduate')], max_length=50, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorEPD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Personal Details',
            },
        ),
        migrations.CreateModel(
            name='employeePermanentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('landMark', models.CharField(max_length=1000)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('pinCode', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('emergencyContactPersonName', models.CharField(blank=True, max_length=1000, null=True)),
                ('emergencyContactPersonNumber', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorEPA', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Permanent Address Details',
            },
        ),
        migrations.CreateModel(
            name='employeeLocalAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('landMark', models.CharField(max_length=1000)),
                ('city', models.CharField(blank=True, max_length=1000, null=True)),
                ('pinCode', models.BigIntegerField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=1000, null=True)),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('localGuardianLandlord', models.CharField(blank=True, max_length=1000, null=True)),
                ('localGuardianLandlordDetails', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorELA', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Local Address Details',
            },
        ),
        migrations.CreateModel(
            name='employeeDepartmentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=1000)),
                ('account', models.CharField(choices=[('Activate', 'Activate'), ('Disable', 'Disable')], default='draft', max_length=10)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorEDD', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeeTypeEDD', to='employeeApp.employeedepartment')),
                ('employeeeType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeeTypeEDD', to='employeeApp.employeetypes')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeeTypeEDD', to='employeeApp.employeegrade')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employeeeTypeEDD', to='employeeApp.employeerole')),
            ],
            options={
                'verbose_name_plural': 'Employee Departmental Details',
            },
        ),
        migrations.CreateModel(
            name='employeeCompanyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyEmail', models.EmailField(max_length=254)),
                ('annualVariable', models.BigIntegerField(blank=True, null=True)),
                ('annualFixed', models.BigIntegerField(blank=True, null=True)),
                ('joiningBonus', models.BigIntegerField(blank=True, null=True)),
                ('annualCTC', models.BigIntegerField(blank=True, null=True)),
                ('retentionBonus', models.BigIntegerField(blank=True, null=True)),
                ('joiningDate', models.DateField(blank=True, null=True)),
                ('dateOfRelieving', models.DateField(blank=True, null=True)),
                ('pfNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('uanNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorECD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Company Details',
            },
        ),
        migrations.CreateModel(
            name='employeeBankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(max_length=1000)),
                ('accountHolder', models.CharField(blank=True, max_length=1000, null=True)),
                ('accountNumber', models.BigIntegerField(blank=True, null=True)),
                ('ifsc_Code', models.CharField(blank=True, max_length=1000, null=True)),
                ('micr_Code', models.CharField(blank=True, max_length=1000, null=True)),
                ('upi', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('accountType', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountTypeEBD', to='employeeApp.employeeaccounttype')),
                ('author', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorEBD', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Bank Details',
            },
        ),
    ]
