# Generated by Django 3.1.7 on 2021-09-29 09:51

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import employeeApp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeeApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorC', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'City',
            },
        ),
        migrations.CreateModel(
            name='companyDetailsFinancialObjs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financialYear', models.PositiveIntegerField(blank=True, choices=[(2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920), (1919, 1919), (1918, 1918), (1917, 1917), (1916, 1916), (1915, 1915), (1914, 1914), (1913, 1913), (1912, 1912), (1911, 1911), (1910, 1910), (1909, 1909), (1908, 1908), (1907, 1907), (1906, 1906), (1905, 1905), (1904, 1904), (1903, 1903), (1902, 1902), (1901, 1901), (1900, 1900), (1899, 1899), (1898, 1898), (1897, 1897), (1896, 1896), (1895, 1895), (1894, 1894), (1893, 1893), (1892, 1892), (1891, 1891), (1890, 1890), (1889, 1889), (1888, 1888), (1887, 1887), (1886, 1886), (1885, 1885), (1884, 1884), (1883, 1883), (1882, 1882), (1881, 1881), (1880, 1880), (1879, 1879), (1878, 1878), (1877, 1877), (1876, 1876), (1875, 1875), (1874, 1874), (1873, 1873), (1872, 1872), (1871, 1871), (1870, 1870), (1869, 1869), (1868, 1868), (1867, 1867), (1866, 1866), (1865, 1865), (1864, 1864), (1863, 1863), (1862, 1862), (1861, 1861), (1860, 1860), (1859, 1859), (1858, 1858), (1857, 1857), (1856, 1856), (1855, 1855), (1854, 1854), (1853, 1853), (1852, 1852), (1851, 1851), (1850, 1850), (1849, 1849), (1848, 1848), (1847, 1847), (1846, 1846), (1845, 1845), (1844, 1844), (1843, 1843), (1842, 1842), (1841, 1841), (1840, 1840), (1839, 1839), (1838, 1838), (1837, 1837), (1836, 1836), (1835, 1835), (1834, 1834), (1833, 1833), (1832, 1832), (1831, 1831), (1830, 1830), (1829, 1829), (1828, 1828), (1827, 1827), (1826, 1826), (1825, 1825), (1824, 1824), (1823, 1823), (1822, 1822), (1821, 1821), (1820, 1820), (1819, 1819), (1818, 1818), (1817, 1817), (1816, 1816), (1815, 1815), (1814, 1814), (1813, 1813), (1812, 1812), (1811, 1811), (1810, 1810), (1809, 1809), (1808, 1808), (1807, 1807), (1806, 1806), (1805, 1805), (1804, 1804), (1803, 1803), (1802, 1802), (1801, 1801)], default=2021, null=True)),
                ('annualLetter', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_40MB])),
                ('annualVariable', models.BigIntegerField(blank=True, null=True)),
                ('annualFixed', models.BigIntegerField(blank=True, null=True)),
                ('joiningBonus', models.BigIntegerField(blank=True, null=True)),
                ('annualCTC', models.BigIntegerField(blank=True, null=True)),
                ('retentionBonus', models.BigIntegerField(blank=True, null=True)),
                ('perksAndBenefits', models.BigIntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorCDFO', to=settings.AUTH_USER_MODEL)),
                ('profileOwnerFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerCDFO', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Company Detail Financial Components',
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorCO', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Country',
            },
        ),
        migrations.CreateModel(
            name='employeeBankDetailsObjs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bankName', models.CharField(blank=True, max_length=1000, null=True)),
                ('accountHolder', models.CharField(blank=True, max_length=1000, null=True)),
                ('accountNumber', models.CharField(blank=True, max_length=1000, null=True)),
                ('ifsc_Code', models.CharField(blank=True, max_length=1000, null=True)),
                ('cancelledCheque', models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB])),
                ('setAsDefault', models.BooleanField(default=False)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Bank Detail Financial Components',
            },
        ),
        migrations.CreateModel(
            name='employeeSalarySlips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(2023, 2023), (2022, 2022), (2021, 2021), (2020, 2020), (2019, 2019), (2018, 2018), (2017, 2017), (2016, 2016), (2015, 2015), (2014, 2014), (2013, 2013), (2012, 2012), (2011, 2011), (2010, 2010), (2009, 2009), (2008, 2008), (2007, 2007), (2006, 2006), (2005, 2005), (2004, 2004), (2003, 2003), (2002, 2002), (2001, 2001), (2000, 2000), (1999, 1999), (1998, 1998), (1997, 1997), (1996, 1996), (1995, 1995), (1994, 1994), (1993, 1993), (1992, 1992), (1991, 1991), (1990, 1990), (1989, 1989), (1988, 1988), (1987, 1987), (1986, 1986), (1985, 1985), (1984, 1984), (1983, 1983), (1982, 1982), (1981, 1981), (1980, 1980), (1979, 1979), (1978, 1978), (1977, 1977), (1976, 1976), (1975, 1975), (1974, 1974), (1973, 1973), (1972, 1972), (1971, 1971), (1970, 1970), (1969, 1969), (1968, 1968), (1967, 1967), (1966, 1966), (1965, 1965), (1964, 1964), (1963, 1963), (1962, 1962), (1961, 1961), (1960, 1960), (1959, 1959), (1958, 1958), (1957, 1957), (1956, 1956), (1955, 1955), (1954, 1954), (1953, 1953), (1952, 1952), (1951, 1951), (1950, 1950), (1949, 1949), (1948, 1948), (1947, 1947), (1946, 1946), (1945, 1945), (1944, 1944), (1943, 1943), (1942, 1942), (1941, 1941), (1940, 1940), (1939, 1939), (1938, 1938), (1937, 1937), (1936, 1936), (1935, 1935), (1934, 1934), (1933, 1933), (1932, 1932), (1931, 1931), (1930, 1930), (1929, 1929), (1928, 1928), (1927, 1927), (1926, 1926), (1925, 1925), (1924, 1924), (1923, 1923), (1922, 1922), (1921, 1921), (1920, 1920), (1919, 1919), (1918, 1918), (1917, 1917), (1916, 1916), (1915, 1915), (1914, 1914), (1913, 1913), (1912, 1912), (1911, 1911), (1910, 1910), (1909, 1909), (1908, 1908), (1907, 1907), (1906, 1906), (1905, 1905), (1904, 1904), (1903, 1903), (1902, 1902), (1901, 1901), (1900, 1900), (1899, 1899), (1898, 1898), (1897, 1897), (1896, 1896), (1895, 1895), (1894, 1894), (1893, 1893), (1892, 1892), (1891, 1891), (1890, 1890), (1889, 1889), (1888, 1888), (1887, 1887), (1886, 1886), (1885, 1885), (1884, 1884), (1883, 1883), (1882, 1882), (1881, 1881), (1880, 1880), (1879, 1879), (1878, 1878), (1877, 1877), (1876, 1876), (1875, 1875), (1874, 1874), (1873, 1873), (1872, 1872), (1871, 1871), (1870, 1870), (1869, 1869), (1868, 1868), (1867, 1867), (1866, 1866), (1865, 1865), (1864, 1864), (1863, 1863), (1862, 1862), (1861, 1861), (1860, 1860), (1859, 1859), (1858, 1858), (1857, 1857), (1856, 1856), (1855, 1855), (1854, 1854), (1853, 1853), (1852, 1852), (1851, 1851), (1850, 1850), (1849, 1849), (1848, 1848), (1847, 1847), (1846, 1846), (1845, 1845), (1844, 1844), (1843, 1843), (1842, 1842), (1841, 1841), (1840, 1840), (1839, 1839), (1838, 1838), (1837, 1837), (1836, 1836), (1835, 1835), (1834, 1834), (1833, 1833), (1832, 1832), (1831, 1831), (1830, 1830), (1829, 1829), (1828, 1828), (1827, 1827), (1826, 1826), (1825, 1825), (1824, 1824), (1823, 1823), (1822, 1822), (1821, 1821), (1820, 1820), (1819, 1819), (1818, 1818), (1817, 1817), (1816, 1816), (1815, 1815), (1814, 1814), (1813, 1813), (1812, 1812), (1811, 1811), (1810, 1810), (1809, 1809), (1808, 1808), (1807, 1807), (1806, 1806), (1805, 1805), (1804, 1804), (1803, 1803), (1802, 1802), (1801, 1801)], default=2021)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='September', max_length=254)),
                ('salarySlip', models.FileField(blank=True, null=True, upload_to='employee/salarySlip/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB])),
                ('dateForStatus', models.DateField(blank=True, default=datetime.date(2021, 9, 29), null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorESS', to=settings.AUTH_USER_MODEL)),
                ('profileOwnerFK', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerESS', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Salary Slips',
            },
        ),
        migrations.CreateModel(
            name='financialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorEFY', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Financial Year',
            },
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorS', to=settings.AUTH_USER_MODEL)),
                ('stateCountry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateCountryS', to='employeeApp.country')),
            ],
            options={
                'verbose_name_plural': 'State',
            },
        ),
        migrations.AlterModelOptions(
            name='employeeaccounttype',
            options={'verbose_name_plural': 'Employee Account Type'},
        ),
        migrations.RemoveField(
            model_name='employeecompanydetails',
            name='annualCTC',
        ),
        migrations.RemoveField(
            model_name='employeecompanydetails',
            name='annualFixed',
        ),
        migrations.RemoveField(
            model_name='employeecompanydetails',
            name='annualVariable',
        ),
        migrations.RemoveField(
            model_name='employeecompanydetails',
            name='joiningBonus',
        ),
        migrations.RemoveField(
            model_name='employeecompanydetails',
            name='retentionBonus',
        ),
        migrations.RemoveField(
            model_name='employeecompanydetails',
            name='uanNumber',
        ),
        migrations.RemoveField(
            model_name='employeedepartmentdetails',
            name='account',
        ),
        migrations.RemoveField(
            model_name='employeelocaladdress',
            name='landMark',
        ),
        migrations.RemoveField(
            model_name='employeepermanentaddress',
            name='landMark',
        ),
        migrations.RemoveField(
            model_name='employeepersonaldetails',
            name='alternateMobileNumber',
        ),
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='aadharCard',
        ),
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='cancelCheque',
        ),
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='uploaddocuments',
            name='panCard',
        ),
        migrations.AddField(
            model_name='employeecompanydetails',
            name='insuranceNumber',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecompanydetails',
            name='profileOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerECD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeedepartmentdetails',
            name='admin',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeedepartmentdetails',
            name='leadership',
            field=models.CharField(blank=True, choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeedepartmentdetails',
            name='profileOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerEDD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeelocaladdress',
            name='profileOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerELA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepermanentaddress',
            name='profileOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerEPA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='bloodGroup',
            field=models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='profileImage',
            field=models.ImageField(blank=True, null=True, upload_to='employee/employee-profile/'),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='profileOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerEPD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='uploadAadhar',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB]),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='uploadDegree',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB]),
        ),
        migrations.AddField(
            model_name='employeepersonaldetails',
            name='uploadPan',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB]),
        ),
        migrations.AddField(
            model_name='uploaddocuments',
            name='offerLetter',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB]),
        ),
        migrations.AddField(
            model_name='uploaddocuments',
            name='profileOwner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerUD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeecompanydetails',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorECD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedepartmentdetails',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorEDD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeedepartmentdetails',
            name='designation',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employeelocaladdress',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorELA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeepermanentaddress',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorEPA', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeepermanentaddress',
            name='emergencyContactPersonNumber',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorEPD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='firstName',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='highestQualification',
            field=models.CharField(blank=True, choices=[('graduate', 'Graduate'), ('postGraduate', 'PostGraduate'), ('underGraduate', 'Graduate')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeepersonaldetails',
            name='maritalStatus',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('seperated', 'Seperated'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='assetDocument',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB]),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorUD', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='experienceLetter',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB]),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='profilePhoto',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB]),
        ),
        migrations.AlterField(
            model_name='uploaddocuments',
            name='recommendationLetter',
            field=models.FileField(blank=True, null=True, upload_to='employee/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf']), employeeApp.models.validate_file_size_10MB]),
        ),
        migrations.DeleteModel(
            name='employeeBankDetails',
        ),
        migrations.AddField(
            model_name='employeebankdetailsobjs',
            name='accountType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accountTypeEBDO', to='employeeApp.employeeaccounttype'),
        ),
        migrations.AddField(
            model_name='employeebankdetailsobjs',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorEBDO', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employeebankdetailsobjs',
            name='profileOwnerFK',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerEBDO', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='city',
            name='cityCountry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityCountryC', to='employeeApp.country'),
        ),
        migrations.AddField(
            model_name='city',
            name='cityState',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityStateC', to='employeeApp.state'),
        ),
        migrations.AlterField(
            model_name='employeelocaladdress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityELA', to='employeeApp.city'),
        ),
        migrations.AlterField(
            model_name='employeelocaladdress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryELA', to='employeeApp.country'),
        ),
        migrations.AlterField(
            model_name='employeelocaladdress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateELA', to='employeeApp.state'),
        ),
        migrations.AlterField(
            model_name='employeepermanentaddress',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cityEPA', to='employeeApp.city'),
        ),
        migrations.AlterField(
            model_name='employeepermanentaddress',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countryEPA', to='employeeApp.country'),
        ),
        migrations.AlterField(
            model_name='employeepermanentaddress',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stateEPA', to='employeeApp.state'),
        ),
    ]
