# Generated by Django 3.1.7 on 2021-10-26 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0005_auto_20211022_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryslips',
            name='dateForStatus',
            field=models.DateField(blank=True, default=datetime.date(2021, 10, 26), null=True),
        ),
    ]
