# Generated by Django 3.1.7 on 2021-11-10 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0009_auto_20211109_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryslips',
            name='dateForStatus',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 10), null=True),
        ),
    ]
