# Generated by Django 3.1.7 on 2021-11-26 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0012_auto_20211122_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryslips',
            name='dateForStatus',
            field=models.DateField(blank=True, default=datetime.date(2021, 11, 26), null=True),
        ),
    ]
