# Generated by Django 3.1.7 on 2022-02-26 19:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0026_auto_20220222_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='countryCode',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employeesalaryslips',
            name='dateForStatus',
            field=models.DateField(blank=True, default=datetime.date(2022, 2, 27), null=True),
        ),
    ]
