# Generated by Django 3.1.7 on 2022-04-12 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeApp', '0030_auto_20220410_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalaryslips',
            name='dateForStatus',
            field=models.DateField(blank=True, default=datetime.date(2022, 4, 12), null=True),
        ),
    ]
