# Generated by Django 3.1.7 on 2021-04-12 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentrateofbondyield',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analystCROBY', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='currentrateofbondyield',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='currentrateofbondyield',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.00, max_digits=1000),
            preserve_default=False,
        ),
    ]
