# Generated by Django 3.1.7 on 2021-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0003_auto_20210415_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockownershipdirector',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=25),
        ),
    ]
