# Generated by Django 3.1.7 on 2021-04-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0004_stockownershipdirector_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocknews',
            name='newsPublishDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
