# Generated by Django 3.1.7 on 2021-04-22 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0005_stocknews_newspublishdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockessentials',
            name='faceValue',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockessentials',
            name='totalShares',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='stockEssentialsAnnual',
        ),
    ]
