# Generated by Django 3.1.7 on 2021-04-22 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0006_auto_20210422_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='financialFigureUnits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareOutstandingNumber', models.CharField(blank=True, choices=[('Thousands', 'Thousands'), ('Lakhs', 'Lakhs'), ('Crores', 'Crores'), ('Millions', 'Millions')], default='Crores', max_length=10, null=True)),
                ('financialNumbers', models.CharField(blank=True, choices=[('Thousands', 'Thousands'), ('Lakhs', 'Lakhs'), ('Crores', 'Crores'), ('Millions', 'Millions')], default='Crores', max_length=10, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analystFFU', to=settings.AUTH_USER_MODEL)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameFFU', to='stockApp.stockbasicdetail')),
                ('verifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifiedByFFU', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Financial - Data Units(cr/lakh.. etc)',
            },
        ),
    ]
