# Generated by Django 3.1.7 on 2021-04-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0009_auto_20210423_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockinvestmentchecklist',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'No Rating'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0, null=True),
        ),
    ]
