# Generated by Django 3.1.7 on 2021-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0010_auto_20210426_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockownership',
            name='genderFrImage',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=25),
        ),
    ]
