# Generated by Django 3.1.7 on 2021-05-07 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0011_stockownership_genderfrimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockAppSpecific',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'For Analyst - Stock App Specific Data',
            },
        ),
        migrations.AlterField(
            model_name='financialfigureunits',
            name='financialNumbers',
            field=models.CharField(blank=True, choices=[('K', 'K'), ('L', 'L'), ('Cr', 'Cr'), ('M', 'M')], default='Crores', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='financialfigureunits',
            name='shareOutstandingNumber',
            field=models.CharField(blank=True, choices=[('K', 'K'), ('L', 'L'), ('Cr', 'Cr'), ('M', 'M')], default='Crores', max_length=10, null=True),
        ),
    ]
