# Generated by Django 3.1.7 on 2021-05-18 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0013_auto_20210514_1607'),
    ]

    operations = [
        migrations.CreateModel(
            name='peersUrlsForSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNamePeersUrl', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'DO NOT TOUCH- FOR SITEMAP-PEERS',
            },
        ),
        migrations.CreateModel(
            name='ownershipUrlsForSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameOwnershipUrl', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'DO NOT TOUCH- FOR SITEMAP-OWNERSHIP',
            },
        ),
        migrations.CreateModel(
            name='newsUrlsForSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameNewsUrl', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'DO NOT TOUCH- FOR SITEMAP-NEWS',
            },
        ),
        migrations.CreateModel(
            name='keyratioUrlsForSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameKRUrl', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'DO NOT TOUCH- FOR SITEMAP-KEYRATIO',
            },
        ),
        migrations.CreateModel(
            name='financialUrlsForSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameFinancialUrl', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'DO NOT TOUCH- FOR SITEMAP-FINANCIAL',
            },
        ),
        migrations.CreateModel(
            name='eventsUrlsForSitemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameEventsUrl', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'DO NOT TOUCH- FOR SITEMAP-EVENTS',
            },
        ),
    ]
