# Generated by Django 3.1.7 on 2021-05-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0014_eventsurlsforsitemap_financialurlsforsitemap_keyratiourlsforsitemap_newsurlsforsitemap_ownershipurls'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockessentials',
            name='essentialsDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
