# Generated by Django 3.1.7 on 2021-06-17 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0017_foundingroundsfigureunits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundingroundsfigureunits',
            old_name='foundingUnitNumbers',
            new_name='fundingUnitNumbers',
        ),
        migrations.AddField(
            model_name='foundingroundsfigureunits',
            name='currencySymbol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='JcurrencySymbolSFR', to='stockApp.currencysymboloptions'),
        ),
    ]
