# Generated by Django 3.1.7 on 2021-06-17 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0018_auto_20210617_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foundingroundsfigureunits',
            old_name='currencySymbol',
            new_name='fundingCurrencySymbol',
        ),
    ]
