# Generated by Django 3.1.7 on 2021-06-17 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0019_auto_20210617_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foundingroundsfigureunits',
            name='fundingCurrencySymbol',
        ),
    ]
