# Generated by Django 3.1.7 on 2021-07-02 15:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0020_remove_foundingroundsfigureunits_fundingcurrencysymbol'),
    ]

    operations = [
        migrations.CreateModel(
            name='fundingDetailsVisibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundedBy', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', max_length=10)),
                ('fundingAmount', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', max_length=10)),
                ('dateOfInvestment', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', max_length=10)),
                ('fundingRound', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', max_length=10)),
                ('fundName', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', max_length=10)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameFDVI', to='stockApp.stockbasicdetail')),
            ],
        ),
    ]
