# Generated by Django 3.1.7 on 2021-07-14 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0021_fundingdetailsvisibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='benGrahamOrDCF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrinsicValueType', models.CharField(choices=[('Ben Graham Value', "Ben Graham's Value"), ('DCF', 'DCF')], default='Ben Graham Value', max_length=100)),
                ('DCFValue', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameBGOD', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Ben Graham Value Or DCF',
            },
        ),
    ]
