# Generated by Django 3.1.7 on 2021-07-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0023_auto_20210723_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockListDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitleResearchReportListing', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaDescriptionResearchReportListing', models.TextField(blank=True, null=True)),
                ('metaKeywordsResearchReportListing', models.TextField(blank=True, null=True)),
                ('tagsResearchReportListing', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'Stock Listing DM Information',
            },
        ),
        migrations.RemoveField(
            model_name='stockadmin',
            name='metaDescriptionResearchReportListing',
        ),
        migrations.RemoveField(
            model_name='stockadmin',
            name='metaKeywordsResearchReportListing',
        ),
        migrations.RemoveField(
            model_name='stockadmin',
            name='metaTitleResearchReportListing',
        ),
        migrations.RemoveField(
            model_name='stockadmin',
            name='tagsResearchReportListing',
        ),
    ]
