# Generated by Django 3.1.7 on 2021-07-23 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0024_auto_20210723_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklistdm',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stocklistdm',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='stocklistdm',
            name='status',
            field=models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', max_length=10),
        ),
        migrations.AddField(
            model_name='stocklistdm',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
