# Generated by Django 3.1.7 on 2021-10-05 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0026_stocklistdm_metafeaturedimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='accountPayable',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='additionalPaidInCapital',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='bankBalanceOtherThanCashEquivalents',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='cashAndCashEquivalents',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='cashAndShortTermInvestments',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='commonStock',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='comprehensiveIncAndOther',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='currentAssets',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='currentInvestments',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='currentLiabilities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='currentPortionOfLeases',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='currentPortionOfLongTermDebt',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='deferredTaxAssest',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='deferredTaxAssetsNet',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='deferredTaxLiabilities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='goodWill',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='intangibleAssestsUnderDevelopment',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='loanAndAdvances',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='longTermInvestments',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='longTermPortionOfLeases',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='marketableSecurities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='minorityInterest',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='netPropertyORPlantOREquipment',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='nonCurrentAssets',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='nonCurrentLiabilities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherCurrentFinancialAssets',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherCurrentLiabilities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherEquity',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherIntangibleAssests',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherNonCurrentAssets',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='otherNonCurrentLiabilities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='prepaidExpenses',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='reservesAndSurplus',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='retainedEarnings',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalAssets',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalCommonSharesOutstanding',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalDeposits',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalEquity',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalInventory',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalLiabilities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalLiabilitiesShareHolderHistory',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalLongTermDebt',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='totalReceivables',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='treasureStock',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbalancesheet',
            name='unearnedRevenue',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockcashflow',
            name='capitalExpenditures',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockcashflow',
            name='cashFromFinancingActivities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockcashflow',
            name='cashFromInvestingActivities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockcashflow',
            name='cashFromOperatingActivities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockcashflow',
            name='changesInWorkingCapital',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockcashflow',
            name='freeCashFlow',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockcashflow',
            name='netChangeInCash',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='DPS',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='basicEPS',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='costOfGoodsSold',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='depreciationAndAmortization',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='dilutedEPS',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='ebidta',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='employeeCost',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='grossProfit',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='interestExpense',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='interestIncome',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='netIncome',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='operatingAndOtherExpenses',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='otherItems',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='otherRevenue',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='payoutRatio',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='pbit',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='pbt',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='powerAndFuelCost',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='rawMaterials',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='sellingAndAdministrativeExpenses',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='taxesAndOtherItems',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockprofitandloss',
            name='totalRevenue',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
    ]
