# Generated by Django 3.1.7 on 2021-10-19 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0027_auto_20211005_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockeventsannouncements',
            name='linkUrlFrAnnouncement',
            field=models.URLField(blank=True, null=True),
        ),
    ]
