# Generated by Django 3.1.7 on 2021-10-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0028_stockeventsannouncements_linkurlfrannouncement'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockownershippattern',
            name='custodians',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockownershippattern',
            name='employees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockownershippattern',
            name='nonPublicInstitutionalHoldings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockownershippattern',
            name='promoters',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockownershippattern',
            name='publicInstitutionalHoldings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockownershippattern',
            name='retail',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
