# Generated by Django 3.1.7 on 2021-10-19 08:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0029_auto_20211019_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='annualReportsDHRP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DHRP_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('DHRP_uploadReport', models.FileField(blank=True, null=True, upload_to='stock/document/uploadReport', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameARDHRP', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Stock Financial - Annual Reports - DHRP',
            },
        ),
    ]
