# Generated by Django 3.1.7 on 2021-10-19 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0030_annualreportsdhrp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualreportsdhrp',
            options={'verbose_name_plural': 'Stock Financial - Annual Reports - DRHP'},
        ),
        migrations.RenameField(
            model_name='annualreportsdhrp',
            old_name='DHRP_heading',
            new_name='DRHP_heading',
        ),
        migrations.RenameField(
            model_name='annualreportsdhrp',
            old_name='DHRP_uploadReport',
            new_name='DRHP_uploadReport',
        ),
    ]
