# Generated by Django 3.1.7 on 2021-11-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0034_auto_20211108_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockownership',
            name='ownershipDescription',
            field=models.TextField(blank=True, null=True),
        ),
    ]
