# Generated by Django 3.1.7 on 2021-11-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0035_stockownership_ownershipdescription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockfinbalancesheetseo',
            old_name='description',
            new_name='balanceSheetDescriptionSEO',
        ),
        migrations.AddField(
            model_name='stockfinbalancesheetseo',
            name='cashFlowDescriptionSEO',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stockfinbalancesheetseo',
            name='profitAndLossDescriptionSEO',
            field=models.TextField(blank=True, null=True),
        ),
    ]
