# Generated by Django 3.1.7 on 2021-11-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0037_stockeventsseo_stocknewsseo'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockeventslegalorders',
            name='linkUrlFrLegalOrders',
            field=models.URLField(blank=True, null=True),
        ),
    ]
