# Generated by Django 3.1.7 on 2021-12-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0039_stockbalancesheetbanknbfc_stockprofitandlossbanknbfc_valuationratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peerscompanylinking',
            options={'verbose_name_plural': 'Peer - Company Linking'},
        ),
        migrations.RemoveField(
            model_name='peerscompanylinking',
            name='ROCE',
        ),
        migrations.RemoveField(
            model_name='peerscompanylinking',
            name='ROE',
        ),
        migrations.RemoveField(
            model_name='peerscompanylinking',
            name='assetTurnoverRation',
        ),
        migrations.RemoveField(
            model_name='peerscompanylinking',
            name='deptToEquity',
        ),
        migrations.RemoveField(
            model_name='peerscompanylinking',
            name='netProfitMargin',
        ),
        migrations.RemoveField(
            model_name='peerscompanylinking',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='peerscompanylinking',
            name='totalFixedAssetTurnoverRatio',
        ),
        migrations.RemoveField(
            model_name='peerscompanylinking',
            name='year',
        ),
        migrations.AddField(
            model_name='peerscompanylinking',
            name='screenerLink',
            field=models.URLField(blank=True, max_length=256, null=True),
        ),
    ]
