# Generated by Django 3.1.7 on 2022-01-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0042_auto_20220103_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockipo',
            name='totalIPOSize',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True),
        ),
    ]
