# Generated by Django 3.1.7 on 2022-01-19 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0043_stockipo_totaliposize'),
    ]

    operations = [
        migrations.CreateModel(
            name='valuesRBIStandards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1800, 1800), (1801, 1801), (1802, 1802), (1803, 1803), (1804, 1804), (1805, 1805), (1806, 1806), (1807, 1807), (1808, 1808), (1809, 1809), (1810, 1810), (1811, 1811), (1812, 1812), (1813, 1813), (1814, 1814), (1815, 1815), (1816, 1816), (1817, 1817), (1818, 1818), (1819, 1819), (1820, 1820), (1821, 1821), (1822, 1822), (1823, 1823), (1824, 1824), (1825, 1825), (1826, 1826), (1827, 1827), (1828, 1828), (1829, 1829), (1830, 1830), (1831, 1831), (1832, 1832), (1833, 1833), (1834, 1834), (1835, 1835), (1836, 1836), (1837, 1837), (1838, 1838), (1839, 1839), (1840, 1840), (1841, 1841), (1842, 1842), (1843, 1843), (1844, 1844), (1845, 1845), (1846, 1846), (1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2022)),
                ('RBI_CARValue', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('RBI_tier1Value', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('RBI_tier2Value', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('RBI_maintenanceMarginRequirement', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Company Values RBI Standards',
            },
        ),
        migrations.AddField(
            model_name='categoryoptions',
            name='fetchScreenerPrice',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='ROCE',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='ROE',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='assetTurnoverRation',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='deptToEquity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='netProfitMargin',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='totalFixedAssetTurnoverRatio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockessentials',
            name='balance_with_RBI',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockessentials',
            name='preference_equity',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockessentials',
            name='screenerLink',
            field=models.URLField(blank=True, help_text='Will work only when Category is "Listed".', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockipo',
            name='totalSubscription',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='PreferenceEquity',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='To be taken from "Value Research".', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='bookValue',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='cashAndShortTermEquivalents',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='currentPrice',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='longTermMarketableSecurities',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='marketCap',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='totalMinorityInterest',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='To be taken from "Value Research".', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockipo',
            name='NII',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockipo',
            name='NonInstitutionalSubscription',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockipo',
            name='QIBSubscription',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockipo',
            name='employeeQuota',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockipo',
            name='retailSubscription',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockipo',
            name='specialQuotaValue',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.CreateModel(
            name='totalShareYearlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('totalShares', models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameTSYD', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Total Share Yearly Data(for snapshot)',
            },
        ),
        migrations.CreateModel(
            name='researchReportFAQs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.CharField(blank=True, max_length=1000, null=True)),
                ('answers', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameRRF', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Research Report FAQs',
            },
        ),
        migrations.CreateModel(
            name='peersCompanyLinkingForBankNBFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenerLink', models.URLField(blank=True, max_length=256, null=True)),
                ('stockStatus', models.CharField(choices=[('Listed', 'Listed'), ('Unlisted', 'Unlisted')], default='Unlisted', max_length=10)),
                ('stockName', models.CharField(blank=True, max_length=256, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNamePCLFNBFC', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Peer - Company Linking For Bank NBFC',
            },
        ),
        migrations.CreateModel(
            name='peerLinkingYearlyDataForBankNBFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1800, 1800), (1801, 1801), (1802, 1802), (1803, 1803), (1804, 1804), (1805, 1805), (1806, 1806), (1807, 1807), (1808, 1808), (1809, 1809), (1810, 1810), (1811, 1811), (1812, 1812), (1813, 1813), (1814, 1814), (1815, 1815), (1816, 1816), (1817, 1817), (1818, 1818), (1819, 1819), (1820, 1820), (1821, 1821), (1822, 1822), (1823, 1823), (1824, 1824), (1825, 1825), (1826, 1826), (1827, 1827), (1828, 1828), (1829, 1829), (1830, 1830), (1831, 1831), (1832, 1832), (1833, 1833), (1834, 1834), (1835, 1835), (1836, 1836), (1837, 1837), (1838, 1838), (1839, 1839), (1840, 1840), (1841, 1841), (1842, 1842), (1843, 1843), (1844, 1844), (1845, 1845), (1846, 1846), (1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2022)),
                ('tier1CapitalRatio', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('tier2CapitalRatio', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('totalAMU', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('RORWA', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('netInterestIncome', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('revenue', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('roa', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('netProfitMargin', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('assetTurnOverRatio', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('ROE', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('CAR', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('netNPA', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('grossNPA', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('peRatio', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('pbRatio', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('NIM', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('CASA', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('DERatio', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('priceByTangibleBookRatio', models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analystPLYDFNBFC', to=settings.AUTH_USER_MODEL)),
                ('screenerCompany', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNamePLYDFNBFC', to='stockApp.peerscompanylinking')),
            ],
            options={
                'verbose_name_plural': 'Peer - Company Linking Year Wise Data for Bank NBFC',
            },
        ),
        migrations.CreateModel(
            name='companyRatios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(choices=[(1800, 1800), (1801, 1801), (1802, 1802), (1803, 1803), (1804, 1804), (1805, 1805), (1806, 1806), (1807, 1807), (1808, 1808), (1809, 1809), (1810, 1810), (1811, 1811), (1812, 1812), (1813, 1813), (1814, 1814), (1815, 1815), (1816, 1816), (1817, 1817), (1818, 1818), (1819, 1819), (1820, 1820), (1821, 1821), (1822, 1822), (1823, 1823), (1824, 1824), (1825, 1825), (1826, 1826), (1827, 1827), (1828, 1828), (1829, 1829), (1830, 1830), (1831, 1831), (1832, 1832), (1833, 1833), (1834, 1834), (1835, 1835), (1836, 1836), (1837, 1837), (1838, 1838), (1839, 1839), (1840, 1840), (1841, 1841), (1842, 1842), (1843, 1843), (1844, 1844), (1845, 1845), (1846, 1846), (1847, 1847), (1848, 1848), (1849, 1849), (1850, 1850), (1851, 1851), (1852, 1852), (1853, 1853), (1854, 1854), (1855, 1855), (1856, 1856), (1857, 1857), (1858, 1858), (1859, 1859), (1860, 1860), (1861, 1861), (1862, 1862), (1863, 1863), (1864, 1864), (1865, 1865), (1866, 1866), (1867, 1867), (1868, 1868), (1869, 1869), (1870, 1870), (1871, 1871), (1872, 1872), (1873, 1873), (1874, 1874), (1875, 1875), (1876, 1876), (1877, 1877), (1878, 1878), (1879, 1879), (1880, 1880), (1881, 1881), (1882, 1882), (1883, 1883), (1884, 1884), (1885, 1885), (1886, 1886), (1887, 1887), (1888, 1888), (1889, 1889), (1890, 1890), (1891, 1891), (1892, 1892), (1893, 1893), (1894, 1894), (1895, 1895), (1896, 1896), (1897, 1897), (1898, 1898), (1899, 1899), (1900, 1900), (1901, 1901), (1902, 1902), (1903, 1903), (1904, 1904), (1905, 1905), (1906, 1906), (1907, 1907), (1908, 1908), (1909, 1909), (1910, 1910), (1911, 1911), (1912, 1912), (1913, 1913), (1914, 1914), (1915, 1915), (1916, 1916), (1917, 1917), (1918, 1918), (1919, 1919), (1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023)], default=2022)),
                ('carValue', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('tier1Value', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('tier2Value', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('maintenanceMarginRequirement', models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameCR', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Company Values Self With RBI Standards',
            },
        ),
    ]
