# Generated by Django 3.1.7 on 2022-02-02 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0044_auto_20220119_1044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockpeers',
            options={'verbose_name_plural': 'Stock Peers - Graph Descriptions'},
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='cashAndShortTermCashEquivalents',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='enterpriseValue',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='evByEbitda',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='marketCapBySales',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='pbRatio',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydata',
            name='peRatio',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='goodwill',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='intangibleAssests',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='loanLossProvision',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='numberOfShares',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AddField(
            model_name='stockipo',
            name='freshIssueNoOfShares',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stockipo',
            name='offerForSaleNoOfShares',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='stockipo',
            name='totalIpoNoOfShares',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='totalshareyearlydata',
            name='shareType',
            field=models.CharField(choices=[('financial_year', 'financial_year'), ('convertible_equity', 'convertible_equity')], default='financial_year', max_length=100),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='ROCE',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='ROE',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='assetTurnoverRation',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='deptToEquity',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='marketCap',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='netProfitMargin',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydata',
            name='totalFixedAssetTurnoverRatio',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='CAR',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='CASA',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='grossNPA',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='netNPA',
            field=models.DecimalField(blank=True, decimal_places=20, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='screenerCompany',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNamePLYDFNBFC', to='stockApp.peerscompanylinkingforbanknbfc'),
        ),
        migrations.AlterField(
            model_name='researchreportfaqs',
            name='answers',
            field=models.TextField(blank=True, help_text="Add 'stock_name_auto' to automatically add the Research Report name.", null=True),
        ),
        migrations.AlterField(
            model_name='researchreportfaqs',
            name='questions',
            field=models.TextField(blank=True, help_text="Add 'stock_name_auto' to automatically add the Research Report name.", null=True),
        ),
        migrations.CreateModel(
            name='stockPeersDescriptionForBankNBFC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('carDescriptionDescription', models.TextField(blank=True, null=True)),
                ('netNPADescription', models.TextField(blank=True, null=True)),
                ('grossNPADescription', models.TextField(blank=True, null=True)),
                ('CASADescription', models.TextField(blank=True, null=True)),
                ('tier1Description', models.TextField(blank=True, null=True)),
                ('tier2Description', models.TextField(blank=True, null=True)),
                ('totalAMUDescription', models.TextField(blank=True, null=True)),
                ('RORWADescription', models.TextField(blank=True, null=True)),
                ('netInterestIncomeDescription', models.TextField(blank=True, null=True)),
                ('revenueDescription', models.TextField(blank=True, null=True)),
                ('roaDescription', models.TextField(blank=True, null=True)),
                ('netProfitMarginDescription', models.TextField(blank=True, null=True)),
                ('assetTurnOverRatioDescription', models.TextField(blank=True, null=True)),
                ('roeDescription', models.TextField(blank=True, null=True)),
                ('PEDescription', models.TextField(blank=True, null=True)),
                ('PBDescription', models.TextField(blank=True, null=True)),
                ('nimDescription', models.TextField(blank=True, null=True)),
                ('debtToEquityRatioDescription', models.TextField(blank=True, null=True)),
                ('pByTBDescription', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('analyst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analystSPDForBNBFCPeer', to=settings.AUTH_USER_MODEL)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameSPDForBNBFCPeer', to='stockApp.stockbasicdetail')),
                ('verifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifiedBySPDForBNBFCPeer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Stock Peers - Bank NBFC Graph Descriptions',
            },
        ),
        migrations.CreateModel(
            name='regulatoryRatios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainDescription', models.TextField(blank=True, null=True)),
                ('carDescription', models.TextField(blank=True, null=True)),
                ('tier1Description', models.TextField(blank=True, null=True)),
                ('tier2Description', models.TextField(blank=True, null=True)),
                ('maintainanceMarginRequirementDescription', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='regulatoryRatiosTitle', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Regulatory Ratios',
            },
        ),
    ]
