# Generated by Django 3.1.7 on 2022-02-03 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0045_auto_20220203_0212'),
    ]

    operations = [
        migrations.CreateModel(
            name='commonFAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions', models.TextField(blank=True, help_text="Add 'stock_name_auto' to automatically add the Research Report name.", null=True)),
                ('answers', models.TextField(blank=True, help_text="Add 'stock_name_auto' to automatically add the Research Report name.", null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Common FAQ',
            },
        ),
        migrations.AlterModelOptions(
            name='researchreportfaqs',
            options={'verbose_name_plural': 'Research Report Specific FAQs'},
        ),
    ]
