# Generated by Django 3.1.7 on 2022-04-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0047_auto_20220410_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='peerlinkingyearlydataforbanknbfc',
            name='marketCap',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='for Unlisted Stock', max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='stockbasicdetail',
            name='showOnPrivateBoutique',
            field=models.BooleanField(default=False),
        ),
    ]
