# Generated by Django 3.1.7 on 2022-05-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0048_auto_20220423_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbasicdetail',
            name='showOnHomePage',
            field=models.BooleanField(default=False),
        ),
    ]
