# Generated by Django 3.1.7 on 2022-06-12 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0049_stockbasicdetail_showonhomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='startupCategoryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Startups Category Options',
            },
        ),
        migrations.CreateModel(
            name='welcomeLoginPopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=1000, null=True)),
                ('letsBeginImage', models.ImageField(blank=True, null=True, upload_to='stock/images/logo')),
                ('letsBeginContent', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('visible', 'visible'), ('hidden', 'hidden')], default='visible', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Lets begin Popup Content',
            },
        ),
        migrations.AddField(
            model_name='stockbasicdetail',
            name='bgImageForStartup',
            field=models.ImageField(blank=True, null=True, upload_to='stock/images/logo'),
        ),
        migrations.AddField(
            model_name='stockbasicdetail',
            name='bgImageForStartupAlt',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stockbasicdetail',
            name='startupCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startupCategorySC', to='stockApp.startupcategoryoptions'),
        ),
    ]
