# Generated by Django 3.1.7 on 2022-07-12 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0051_auto_20220625_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockDeckAndDocs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOrYear', models.CharField(blank=True, max_length=1000, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('uploadPDFOrPPT', models.FileField(blank=True, null=True, upload_to='stock/document/uploadReport', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptm', 'pptx'])])),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameARDD', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Stock Financial - Deck and Documents',
            },
        ),
    ]
