# Generated by Django 3.1.7 on 2022-08-04 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0052_stockdeckanddocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbasicdetail',
            name='get_funds_in',
            field=models.CharField(blank=True, choices=[('Planify Enterprise', 'Planify Enterprise'), ('Planify Capital', 'Planify Capital')], default='Planify Enterprise', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='stockbasicdetail',
            name='min_invest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stockdeckanddocs',
            name='uploadPDFOrPPT',
            field=models.FileField(blank=True, null=True, upload_to='stock/document/uploadReport', validators=[django.core.validators.FileExtensionValidator(['pdf', 'ppt', 'pptm', 'pptx', 'jpeg', 'jpg', 'png'])]),
        ),
    ]
