# Generated by Django 3.1.7 on 2022-08-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0053_auto_20220804_2322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockbasicdetail',
            name='get_funds_in',
            field=models.CharField(blank=True, choices=[('Planify Enterprise', 'Planify Enterprise'), ('Planify Capital', 'Planify Capital')], default='Planify Capital', max_length=256, null=True),
        ),
    ]
