# Generated by Django 3.1.7 on 2022-08-20 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0054_auto_20220806_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginReminderPopup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleOne', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentOne', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleOneImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleOneImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('titleTwo', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentTwo', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleTwoImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleTwoImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('titleThree', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentThree', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleThreeImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleThreeImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('titleFour', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentFour', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleFourImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleFourImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('titleFive', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentFive', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleFiveImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleFiveImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('titleSix', models.CharField(blank=True, max_length=1000, null=True)),
                ('contentSix', models.CharField(blank=True, max_length=1000, null=True)),
                ('titleSixImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('titleSixImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('bannerImg', models.ImageField(blank=True, null=True, upload_to='login/images')),
                ('bannerImg_AltTag', models.CharField(blank=True, max_length=100, null=True)),
                ('videoID', models.CharField(blank=True, max_length=1000, null=True)),
                ('videoTitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('videoContent', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Login Reminder Popup Data',
            },
        ),
        migrations.AddField(
            model_name='stockbasicdetail',
            name='headingForStartup',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='stockbasicdetail',
            name='planifyCertified',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='stockbasicdetail',
            name='amount_To_Raise',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockbasicdetail',
            name='investment_Raised',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stockbasicdetail',
            name='jump_Start',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
