# Generated by Django 3.1.7 on 2022-09-15 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0055_auto_20220820_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockownershipdirector',
            name='delta',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='highLights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='stock/images/highLightsicon')),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameHL', to='stockApp.stockbasicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='deck_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('page_description', models.TextField(blank=True, null=True)),
                ('page_image', models.FileField(blank=True, null=True, upload_to='stock/images/image')),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNamedeck_image', to='stockApp.stockbasicdetail')),
            ],
        ),
        migrations.CreateModel(
            name='deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dec_description', models.TextField(blank=True, null=True)),
                ('dec_ppt', models.FileField(blank=True, null=True, upload_to='stock/images/deck')),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNamedeck', to='stockApp.stockbasicdetail')),
            ],
        ),
    ]
