# Generated by Django 3.1.7 on 2022-09-21 10:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0056_auto_20220916_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deck',
            options={'verbose_name_plural': 'deck'},
        ),
        migrations.AlterModelOptions(
            name='deck_images',
            options={'verbose_name_plural': 'deck_images'},
        ),
        migrations.AlterModelOptions(
            name='highlights',
            options={'verbose_name_plural': 'Highlights'},
        ),
        migrations.RemoveField(
            model_name='deck_images',
            name='page_id',
        ),
        migrations.RemoveField(
            model_name='deck_images',
            name='stockProfileName',
        ),
        migrations.AddField(
            model_name='deck_images',
            name='deckname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deckimages', to='stockApp.deck'),
        ),
        migrations.AddField(
            model_name='deck_images',
            name='tag',
            field=models.TextField(null=True),
        ),
        migrations.CreateModel(
            name='annualReportsDHRPImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DRHPimage_heading', models.CharField(blank=True, max_length=500, null=True)),
                ('DRHPimage_uploadReport', models.FileField(blank=True, null=True, upload_to='stock/document/imageReport')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameARDHRPImage', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Stock Financial -DRHP-Image',
            },
        ),
    ]
