# Generated by Django 3.1.7 on 2022-10-07 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0057_auto_20220921_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockbasicdetail',
            name='showOnPitchPage',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign_description', models.TextField(blank=True, default='', null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('isActive', models.BooleanField(default=True)),
                ('stockProfileName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stockProfileNameCampaign', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'campaign',
            },
        ),
    ]
