# Generated by Django 3.1.7 on 2022-09-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartApp', '0002_auto_20220827_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='investMentPrice',
            field=models.DecimalField(blank=True, decimal_places=50, default=0, max_digits=1000, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
