# Generated by Django 3.1.7 on 2021-06-25 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlogApp', '0002_blognewsdetaileddm_blognewslistingdm'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogWebNewsListingDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitleNews', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaDescriptionNews', models.TextField(blank=True, null=True)),
                ('metaKeywordsNews', models.TextField(blank=True, null=True)),
                ('tagsNews', models.CharField(blank=True, max_length=1000, null=True)),
                ('featuredImage', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Blog Web News Listing DM',
            },
        ),
    ]
