# Generated by Django 3.1.7 on 2021-07-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlogApp', '0005_newsheadingwebdm'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='pdfForNews',
            field=models.FileField(blank=True, null=True, upload_to='blog/newsPDFS'),
        ),
        migrations.AddField(
            model_name='blognews',
            name='pptForNews',
            field=models.FileField(blank=True, null=True, upload_to='blog/newsPPTS'),
        ),
    ]
