# Generated by Django 3.1.7 on 2021-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0021_fundingdetailsvisibility'),
        ('newsBlogApp', '0006_auto_20210703_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='relatedResearchReports',
            field=models.ManyToManyField(blank=True, related_name='relatedResearchReportsBN', to='stockApp.stockBasicDetail'),
        ),
    ]
