# Generated by Django 3.1.7 on 2021-07-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlogApp', '0008_blognews_excerptcontent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blognews',
            options={'verbose_name_plural': 'Blog News Profile'},
        ),
    ]
