# Generated by Django 3.1.7 on 2021-07-14 15:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlogApp', '0009_auto_20210713_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='dateOfNews',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
