# Generated by Django 3.1.7 on 2021-07-14 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlogApp', '0010_auto_20210714_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blognews',
            name='dateOfNews',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
