# Generated by Django 3.1.7 on 2021-09-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsBlogApp', '0012_blognews_researchreportforlogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blognews',
            name='imageUpload',
            field=models.ImageField(blank=True, null=True, upload_to='blog/images'),
        ),
    ]
