# Generated by Django 3.1.7 on 2021-06-17 17:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='videoShortsCategoryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorVSCO', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Videos Shorts Category Details',
            },
        ),
        migrations.CreateModel(
            name='videoShortsSubCategoryOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorVideoShortsSCO', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='videoShortsApp.videoshortscategoryoptions')),
            ],
            options={
                'verbose_name_plural': 'Videos Shorts Sub Category Details',
            },
        ),
        migrations.CreateModel(
            name='blogVideosShorts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(max_length=250, unique_for_date='publish')),
                ('blogImage', models.ImageField(blank=True, null=True, upload_to='blog/images')),
                ('blogVideo', models.FileField(blank=True, null=True, upload_to='blog/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4'])])),
                ('videoLink', models.CharField(blank=True, max_length=250, null=True)),
                ('dateOfVideo', models.DateTimeField(blank=True, null=True)),
                ('subTitle', models.CharField(blank=True, max_length=250, null=True)),
                ('content1', models.TextField(blank=True, null=True)),
                ('content2', models.TextField(blank=True, null=True)),
                ('content3', models.TextField(blank=True, null=True)),
                ('content4', models.TextField(blank=True, null=True)),
                ('content5', models.TextField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorBVShorts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, related_name='categoryBV', to='videoShortsApp.videoShortsCategoryOptions')),
                ('subCategory', models.ManyToManyField(blank=True, related_name='subCategoryBV', to='videoShortsApp.videoShortsSubCategoryOptions')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name_plural': 'Video Shorts Profile',
            },
        ),
    ]
