# Generated by Django 3.1.7 on 2021-06-22 11:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoShortsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='blogPageSectionsOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayedCategories', models.ManyToManyField(blank=True, related_name='categoryDCBPSOVS', to='videoShortsApp.videoShortsCategoryOptions')),
                ('displayedSubCategories', models.ManyToManyField(blank=True, related_name='subCategoryDCBPSOVS', to='videoShortsApp.videoShortsSubCategoryOptions')),
                ('lastUpdateBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authorDCBPSOVS', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Do Not Touch This Model-1',
            },
        ),
    ]
