# Generated by Django 3.1.7 on 2021-06-22 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoShortsApp', '0002_blogpagesectionsordering'),
    ]

    operations = [
        migrations.DeleteModel(
            name='blogPageSectionsOrdering',
        ),
    ]
