# Generated by Django 3.1.7 on 2021-06-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoShortsApp', '0004_blogshortsdetaileddm_blogshortslistingdm'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogvideosshorts',
            old_name='dateOfVideo',
            new_name='releaseDate',
        ),
    ]
