# Generated by Django 3.1.7 on 2021-07-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0021_fundingdetailsvisibility'),
        ('videoShortsApp', '0006_shortsheadingdm'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideosshorts',
            name='relatedResearchReports',
            field=models.ManyToManyField(blank=True, related_name='relatedResearchReportsBVS', to='stockApp.stockBasicDetail'),
        ),
        migrations.AlterField(
            model_name='blogvideosshorts',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='categoryBVS', to='videoShortsApp.videoShortsCategoryOptions'),
        ),
        migrations.AlterField(
            model_name='blogvideosshorts',
            name='subCategory',
            field=models.ManyToManyField(blank=True, related_name='subCategoryBVS', to='videoShortsApp.videoShortsSubCategoryOptions'),
        ),
    ]
