# Generated by Django 3.1.7 on 2021-07-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoShortsApp', '0007_auto_20210712_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideosshorts',
            name='excerptContent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
