# Generated by Django 3.1.7 on 2021-07-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoShortsApp', '0008_blogvideosshorts_excerptcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogvideosshorts',
            name='featuredShots',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=50),
        ),
    ]
