# Generated by Django 3.1.7 on 2021-07-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoShortsApp', '0009_blogvideosshorts_featuredshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogvideosshorts',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
    ]
