# Generated by Django 3.1.7 on 2022-01-19 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='redirectBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=1000, unique=True)),
                ('destination', models.URLField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'Redirect Urls Buckets',
            },
        ),
        migrations.CreateModel(
            name='redirectCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientIP', models.TextField(blank=True, null=True)),
                ('redirectInst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redirectInstRC', to='brokenRedirectApp.redirectbucket')),
            ],
            options={
                'verbose_name_plural': 'Redirect Links Count with IP',
            },
        ),
    ]
