# Generated by Django 3.1.7 on 2021-07-15 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0022_bengrahamordcf'),
        ('articleBlogApp', '0002_blogarticles_excerptcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticles',
            name='relatedResearchReports',
            field=models.ManyToManyField(blank=True, related_name='relatedResearchReportsBA', to='stockApp.stockBasicDetail'),
        ),
    ]
