# Generated by Django 3.1.7 on 2022-01-03 05:57

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('articleBlogApp', '0003_blogarticles_relatedresearchreports'),
    ]

    operations = [
        migrations.CreateModel(
            name='articleDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaDescription', models.CharField(blank=True, max_length=1000, null=True)),
                ('tags', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaFeaturedImage', models.ImageField(blank=True, null=True, upload_to='images/documents', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])])),
                ('metaKeywords', models.CharField(blank=True, max_length=1000, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='draft', max_length=50)),
            ],
        ),
    ]
