# Generated by Django 3.1.7 on 2022-08-04 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0053_auto_20220804_2322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_on', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(decimal_places=50, max_digits=1000)),
                ('order_id', models.TextField(blank=True, null=True, unique=True)),
                ('checksum', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_MID', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_txnID', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_txnAmount', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_paymentMode', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_currency', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_txnDate', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_status', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_repsonseCode', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_responseMsg', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_gatewayName', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_bankTxnID', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_bankName', models.CharField(blank=True, max_length=1000, null=True)),
                ('pg_checkSubHash', models.CharField(blank=True, max_length=1000, null=True)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('selected_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Order Transaction Details',
            },
        ),
    ]
