# Generated by Django 3.1.7 on 2021-07-13 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaBlogApp', '0002_blogmedia_excerptcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmedia',
            name='contentList',
        ),
    ]
