# Generated by Django 3.1.7 on 2021-07-23 14:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mediaBlogApp', '0003_remove_blogmedia_contentlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediaBlogDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metaTitleListing', models.CharField(blank=True, max_length=1000, null=True)),
                ('metaDescriptionListing', models.TextField(blank=True, null=True)),
                ('metaKeywordsListing', models.TextField(blank=True, null=True)),
                ('tagsListing', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='draft', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Media Listing DM Information',
            },
        ),
    ]
