# Generated by Django 3.1.7 on 2022-02-26 19:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit_autosuggest.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0046_auto_20220204_0018'),
        ('videoBlogApp', '0020_auto_20220227_0030'),
        ('videoShortsApp', '0010_auto_20210715_2050'),
        ('newsBlogApp', '0013_blognews_imageupload'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('articleBlogApp', '0004_articledm'),
    ]

    operations = [
        migrations.CreateModel(
            name='metaDetailForDM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('static_page', models.CharField(blank=True, choices=[('homepage', 'homepage'), ('aboutpage', 'aboutpage'), ('contactpage', 'contactpage'), ('careerpage', 'careerpage'), ('teampage', 'teampage'), ('seedFundingPage', 'seedFundingPage'), ('earlyFundingPage', 'earlyFundingPage'), ('growthFundingPage', 'growthFundingPage'), ('sellYourStartupPage', 'sellYourStartupPage'), ('sellESOPPage', 'sellESOPPage'), ('seedFundingSignupPage', 'seedFundingSignupPage'), ('earlyFundingSignupPage', 'earlyFundingSignupPage'), ('growthFundingSignupPage', 'growthFundingSignupPage'), ('sellYourStartupSignupPage', 'sellYourStartupSignupPage'), ('sellESOPSignupPage', 'sellESOPSignupPage'), ('preIPOPage', 'preIPOPage'), ('blogHomePage', 'blogHomePage'), ('videoBlogListPage', 'videoBlogListPage'), ('newsBlogListPage', 'newsBlogListPage'), ('stockListPage', 'stockListPage'), ('mediaListPage', 'mediaListPage'), ('videoShortsListPage', 'videoShortsListPage'), ('newsFeedListPage', 'newsFeedListPage'), ('articleListPage', 'articleListPage'), ('buyPreIPOPage', 'buyPreIPOPage'), ('channelPartnerPage', 'channelPartnerPage'), ('channelPartnerSignupPage', 'channelPartnerSignupPage'), ('videoBlog', 'videoBlog'), ('shortsBlog', 'shortsBlog'), ('articleBlog', 'articleBlog'), ('newsBlog', 'newsBlog'), ('researchReports', 'researchReports')], max_length=256, null=True)),
                ('research_report_pages', models.CharField(blank=True, choices=[('snapshot', 'snapshot'), ('key-ratio', 'key-ratio'), ('peers', 'peers'), ('financials', 'financials'), ('ownership', 'ownership'), ('news', 'news'), ('events', 'events')], max_length=256, null=True)),
                ('meta_title', models.CharField(blank=True, max_length=1000, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='dm/featured-images')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Pending For Review', 'Pending For Review'), ('Feedback Shared', 'Feedback Shared'), ('Rejected', 'Rejected')], default='Draft', max_length=50)),
                ('articles_blog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_blog_blogBVDDM', to='articleBlogApp.blogarticles')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorBVDDM', to=settings.AUTH_USER_MODEL)),
                ('meta_tags', taggit_autosuggest.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('news_blog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_blog_blogBVDDM', to='newsBlogApp.blognews')),
                ('research_report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_reportBVDDM', to='stockApp.stockbasicdetail')),
                ('video_blog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_blogBVDDM', to='videoBlogApp.blogvideos')),
                ('video_shorts_blog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='video_shorts_blogBVDDM', to='videoShortsApp.blogvideosshorts')),
            ],
            options={
                'verbose_name_plural': 'Meta Description For Whole Website',
            },
        ),
    ]
