# Generated by Django 3.1.7 on 2022-03-27 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmFormsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadetailfordm',
            name='end_point',
            field=models.TextField(blank=True, null=True),
        ),
    ]
