# Generated by Django 3.1.7 on 2022-09-15 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='otp_authentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(blank=True, max_length=256, null=True)),
                ('country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('email', models.CharField(blank=True, max_length=256, null=True)),
                ('otp', models.CharField(blank=True, max_length=256, null=True)),
                ('login_pin', models.CharField(blank=True, max_length=256, null=True)),
                ('requested_on', models.CharField(choices=[('Mobile', 'Mobile'), ('Email', 'Email')], default='Email', max_length=10)),
                ('requested_for', models.CharField(choices=[('Login', 'Login'), ('Signup', 'Signup'), ('Verify', 'Verify')], default='Signup', max_length=10)),
                ('email_verified', models.BooleanField(default=False)),
                ('phone_verified', models.BooleanField(default=False)),
                ('google_verified', models.BooleanField(default=False)),
                ('linkedin_verified', models.BooleanField(default=False)),
                ('onboarding_popup', models.BooleanField(default=False)),
                ('author', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('userProfile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userProfile_otp_authentication_authV2', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'OTP Authentication',
            },
        ),
    ]
