# Generated by Django 3.1.7 on 2022-05-27 20:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0049_stockbasicdetail_showonhomepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='stockDailyUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=1000, null=True)),
                ('minLotSize', models.BigIntegerField(blank=True, null=True)),
                ('ratings', models.CharField(blank=True, max_length=1000, null=True)),
                ('available', models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available')], default='Available', max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authorSDUp', to=settings.AUTH_USER_MODEL)),
                ('stockProfile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockNameSDUp', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Pre IPO Stock Daily Updates Data',
            },
        ),
    ]
