# Generated by Django 3.1.7 on 2022-06-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investorApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investorpersonaldetails',
            name='email',
        ),
        migrations.AddField(
            model_name='investorbankdetails',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='investmentdetails',
            name='presentPortfolio',
            field=models.CharField(blank=True, choices=[('< ₹ 1 Lac', '< ₹ 1 Lac'), ('₹ 1 - 5 Lac', '₹ 1 - 5 Lac'), ('₹ 5 - 10 Lac', '₹ 5 - 10 Lac'), ('₹ 10 - 25 Lac', '₹ 10 - 25 Lac'), ('₹ 25 - 50 Lac', '₹ 25 - 50 La'), ('₹ 50 - 100 Lac', '₹ 50 - 100 Lac'), ('₹ 1 - 5 Crores', '₹ 1 - 5 Crores'), ('₹ 5 - 10 Crores', '₹ 5 - 10 Crores'), ('₹ 10 - 25 Crores', '₹ 10 - 25 Crores'), ('₹ 25 - 50 Crores', '₹ 25 - 50 Crores'), ('₹ 50 - 100 Crores', '₹ 50 - 100 Crores'), ('₹ 100 + Crores', '₹ 100 + Crores')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetails',
            name='accountHolder',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetails',
            name='accountNumber',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='investordmatdetails',
            name='clientID',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
