# Generated by Django 3.1.7 on 2022-06-21 16:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investorApp', '0002_auto_20220612_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentdetails',
            name='investPorfolio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='investordmatdetails',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investorbankdetails',
            name='cancelledCheque',
            field=models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='investorbankdetails',
            name='is_default',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='investordmatdetails',
            name='dmatClientMasterReport',
            field=models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='investorpersonaldetails',
            name='uploadAadhar',
            field=models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png', 'bmp'])]),
        ),
        migrations.AlterField(
            model_name='investorpersonaldetails',
            name='uploadPan',
            field=models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png', 'bmp'])]),
        ),
    ]
