# Generated by Django 3.1.7 on 2022-09-15 19:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockApp', '0056_auto_20220916_0055'),
        ('investorApp', '0005_channelpartnerlist_dealerlist_investorportfoliomanagedby_investorsource_investorsourcedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerTU', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'temp users',
            },
        ),
        migrations.CreateModel(
            name='tempTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=50, max_digits=1000, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('investMentPrice', models.DecimalField(blank=True, decimal_places=50, max_digits=1000, null=True)),
                ('txn_made_by', models.CharField(choices=[('Self', 'Self'), ('PaymentGateway', 'PaymentGateway')], default='Self', max_length=1000)),
                ('trxnDate', models.DateTimeField(blank=True, null=True)),
                ('publish', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('made_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tempTransactionTT', to='investorApp.tempuser')),
                ('selected_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactionStockTT', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Temprory Order Transaction Details',
            },
        ),
        migrations.CreateModel(
            name='investorPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('transactionDate', models.DateTimeField(blank=True, null=True)),
                ('investorStockPrice', models.IntegerField(blank=True, null=True)),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('profileOwner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profileOwnerIPLO', to=settings.AUTH_USER_MODEL)),
                ('stock_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investorPortfolioSTCK', to='stockApp.stockbasicdetail')),
            ],
            options={
                'verbose_name_plural': 'Investor Portfolio',
            },
        ),
    ]
