# Generated by Django 3.1.7 on 2022-10-07 17:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('investorApp', '0006_investorportfolio_temptransaction_tempuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='shareBookTransactionsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_DpID', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_clientID', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_brokerName', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_Quantity', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_ISIN', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_resonCode', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_consideration', models.BigIntegerField(blank=True, null=True)),
                ('sb_buyerName', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_buyerBank', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_accountNo', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_paymentReference', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_KYC', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_stockName', models.CharField(blank=True, max_length=1000, null=True)),
                ('sb_shareTransfer', models.CharField(blank=True, max_length=100, null=True)),
                ('sb_executionDate', models.DateTimeField(blank=True, null=True)),
                ('sb_uploadTransferRequest', models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png', 'bmp'])])),
                ('publish', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('related_investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shareBookTransactionSBTL', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Share Book Transaction List',
            },
        ),
        migrations.CreateModel(
            name='shareBookStatusDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sb_company', models.CharField(blank=True, max_length=100, null=True)),
                ('sb_depository', models.CharField(blank=True, max_length=100, null=True)),
                ('sb_shareTransferStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('sb_uploadFile', models.FileField(blank=True, null=True, upload_to='investor/documents/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpeg', 'jpg', 'png', 'bmp'])])),
                ('publish', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('tansaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shareBookTransactionSBT', to='investorApp.sharebooktransactionslist')),
            ],
            options={
                'verbose_name_plural': 'Share Book Transaction Status List',
            },
        ),
    ]
